#pragma once
#include <Windows.h>
#include <string>
#pragma pack(1)

#define OMOCK_WHNUM 19
#define BLACKSTONE	true
#define WHITESTONE	false
#define EMPTYBLOCK	10
#define CHATBUF 256

using namespace std;
enum SCENE_INDEX
{
	SCENE_LOBBY,
	SCENE_GAME,
	SCENE_END
};

enum SORT_OF_CALCULATION
{
	SORT_OF_CALCULATION_VICTORY,
	SORT_OF_CALCULATION_SIXSTONES,
	SORT_OF_CALCULATION_33,
	SORT_OF_CALCULATION_ORDINARY,
	SORT_OF_CALCULATION_END
};

enum PACKET_INDEX
{
	PACKET_INDEX_LOGIN_RESULT,
	PACKET_INDEX_PLAYER_INFO,
	PACKET_INDEX_PLAYER_MAP,
	PACKET_INDEX_GAMERESULT,
	PACKET_INDEX_STRING,
	PACKET_INDEX_COMMAND,
	PACKET_INDEX_END
};
enum STONE_COLOR
{
	STONE_COLOR_WHITE,
	STONE_COLOR_BLACK,
	STONE_COLOR_EMPTY,
	STONE_COLOR_END
};

enum COMMAND_INDEX
{
	COMMAND_BLACKTURN,
	COMMAND_WHITETURN,
	COMMAND_BLACKWIN,
	COMMAND_WHITEWIN,
	COMMAND_RETRY_PUT_33_BLACK,
	COMMAND_RETRY_PUT_33_WHITE,
	COMMAND_RETRY_PUT_6_BLACK,
	COMMAND_RETRY_PUT_6_WHITE,

	COMMAND_START_GAME,
	COMMAND_RESET_GAME,
	COMMAND_END_OF_GAME
};

struct PACKET_HEADER
{
	WORD wPacketIndex;
	WORD wLen;
	bool bTrashPacket;
};

struct PACKET_LOGIN_RESULT
{
	PACKET_HEADER header;
	bool bStoneColor;
	WORD Map[OMOCK_WHNUM][OMOCK_WHNUM];
};


struct POINTXY
{
	unsigned short x;
	unsigned short y;
};

struct PACKET_PUTXY_INFO
{
	PACKET_HEADER header;
	bool bStoneColor;
	POINTXY PlayerXY;
};

struct PACKET_STRING
{
	PACKET_HEADER header;
	char str[256];
};

struct PACKET_RESULT
{
	PACKET_HEADER header;
	bool bGameWin;
};

struct PACKET_COMMAND
{
	PACKET_HEADER header;
	unsigned char ucCommand;
};
#pragma pack()

